sudo: false

language: node_js
node_js:
    - "4.2"
    - "5.0"
    - "6.9.4"
    - "7.4.0"

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

script: "grunt"

after_success: istanbul-coveralls
